### ISSUE TITLE
Race-->Call It

### ISSUE THREAD

**Issue by calvertcruz** [evanfarrar/opensprints#77] opened 2009-09-20 05:29 UTC
Clicking this button returns to the main menu screen. It should take the user to the Get ready screen.

**Comment by evanfarrar** [comment] 2009-09-20 05:45
Really?!? It takes me to the winner screen. If someone has finished but someone else hasn't, the call it button should declare the finisher the winner and mark the other as "DNF". 

I did notice that double clicking very fast caused me to go to the main screen because a button pops up right where the call it button was. When running a real race (not in mock mode) that screen will be a little more responsive, so you might be be less inclined to doubleclick.

**Comment by jonfen** [comment] 2009-09-20 07:51
I confirmed Cal's find.  If you start the race, and then immediately click "Call It" it goes back to a blank screen that just gives you two buttons at the top "Return to Main Menu" and "back to event"

**Comment by evanfarrar** [comment] 2009-09-21 02:11
I still can't replicate...I don't know what to do. Can you guys try this with the electronics? or maybe try it after a second or two? Hit alt-/ and read me the error console? I've done it probably a dozen times with no effect.

**Comment by lukeorland** [comment] 2009-09-21 05:07
i've had no luck replicating this. I can't recall ever seeing that happening, and i was just testing with build 0.2-29.

**Comment by lukeorland** [comment] 2009-09-21 21:58
clicking this button goes to the Win Screen, with both riders finishing DNF. Tested again in build 0.2-38. closing. please reopen if this happens again.

**Closed as completed by lukeorland** 2009-09-21 21:58 UTC
Labels: Bug, Race
