### ISSUE TITLE
Event-->Race-->Edit Race: adding third racer freezes software

### ISSUE THREAD

**Issue by calvertcruz** [evanfarrar/opensprints#68] opened 2009-09-20 05:12 UTC
If the race is configured for 2 bikes, this form still allows you to add a third racer which either freezes the software or goes to a blank screen.

**Comment by evanfarrar** [comment] 2009-09-21 01:57
This is a duplicate of #73, which was fixed in 0.2-28

**Closed as completed by evanfarrar** 2009-09-21 01:57 UTC
Labels: Events, Bug, Race
